### ISSUE TITLE
Municipio Alegría asignado a La libertad

### ISSUE THREAD

**Issue by 0noel0** [SamBurgos/DepMun-El-Salvador#2]
Alegría (id: 42) está asignado al cod 4 y debería ser al 11. Por lo demás gracias por el aporte, ya se ahorra uno digitarlo.

**Comment by SamBurgos** [comment]
Hola 0noel0, lamento no haber podido revisar esto con tiempo, acabo de realizar una actualización en el archivo que me dices y ya lo tengo solventado. Espero que esto te ayude 53810ca2b6cc848ad323ed83a5394ca3a2b631a1
